### ISSUE TITLE
Support for AudioStreamRandomizer

### ISSUE THREAD

**Issue by JustinHardage** [nathanhoad/godot_sound_manager#16]
**Is your feature request related to a problem? Please describe.**
The standard AudioStreamPlayer will play a different stream each time it plays when given an AudioStreamRandomizer. You can stop and start it multiple times in a row to get randomized streams. SoundManager does not not stop the current stream when treated similarly.

**Describe the solution you'd like**
I would like SoundManager to treat AudioStreamRandomizer as a special case, so that users can play the same AudioStreamRandomizer resource multiple times to get randomized results.

In particular, I think the combination of checking for currently playing resource and the crossfade timer make it hard to diagnose the problem for new users. https://github.com/nathanhoad/godot_sound_manager/blob/41df4fa3853dd649ec5a760b09a2c1470f1eab1e/addons/sound_manager/music.gd#L14

**Describe alternatives you've considered**
The user may wait longer than the crossfade timer between stop_music() and play_music(), and SoundManager will correctly pick up a randomized stream from AudioStreamRandomizer.

E.g. `await get_tree().create_timer(0.2).timeout`

**Additional context**
I'm new to the AudioStreamRandomizer resource and find it a bit limiting. I'm not sure if my difficulty here is my ignorance of SoundManager or the Randomizer. If you have best practices recommendations for a looping music player that randomly selects a new stream at the end of the previous stream, I'd love to learn about them!

**Comment by nathanhoad** [comment]
I've added a special case for `AudioStreamRandomizer`. Let me know if this solves what you're trying to do.

**Comment by JustinHardage** [comment]
Yeah, I think that does it

That's a big help, now I can take out that await code. Thanks!
