### ISSUE TITLE
Continuous sounds

### ISSUE THREAD

**Issue by JUSTCAMH** [nathanhoad/godot_sound_manager#21]
**Is your feature request related to a problem? Please describe.**
A way to play a looping sound that needs to be turned on or off. Examples include footsteps, rain, whooshing sounds, water ambience, jetpacks and rockets. For all of these, there is a looping sound that in some cases should be on, and in others should fade out.

**Describe the solution you'd like**
A function to ‘set_continuous_sound_active’, which takes in the sound, a bool and optionally a fade time. When set to true, that sound will fade in. When set to false, the sound will fade out. Multiple different continuous sounds can be played at the same time. In the process function I could have something like the following:
`SoundManager.set_continuous_sound_active(footsteps, player.is_walking, 0.1)`

**Describe alternatives you've considered**
Tried using the music system to handle these continuous sounds, however it seems only one music track can be running at once. If music were used, this would play on the wrong bus by default and would require a line to turn it on and another to turn it off (rather than a single line that takes in a bool).

**Comment by nathanhoad** [comment]
I'll need this for my game soon too. I'll have a look at implementing something when I get a chance.

**Comment by nathanhoad** [comment]
@JUSTCAMH have a look at https://github.com/nathanhoad/godot_sound_manager/pull/24 and see if that is the kind of thing you're thinking of.

**Comment by JUSTCAMHRara** [comment]
Oh wow yes, from the docs that sounds perfect, thanks!
