### ISSUE TITLE
Emit signal when playback of SFX ends?

### ISSUE THREAD

**Issue by MichaelGame-Dev** [nathanhoad/godot_sound_manager#23]
**Is your feature request related to a problem? Please describe.**
I want to playback random sound effects in a folder and start a timer after the sound effect ends. They are variable length so I can't just add that to the timer as a buffer. I want to be able to play sound effects at a set interval.

**Describe the solution you'd like**
There's a finished signal for AudioStreamPlayer, even being able to tap into that would work

**Describe alternatives you've considered**
Setting a longer timer, it's what I will do for now.

**Comment by nathanhoad** [comment]
`SoundManager.play_sound` returns the `AudioStreamPlayer` that will play the sound so you can `await` the `finished` signal of that player.
