### ISSUE TITLE
[Bugs] `SoundManager.set_sound_volume` also `SoundManager.set_music_volume`

### ISSUE THREAD

**Issue by NNBnh** [nathanhoad/godot_sound_manager#7]
https://github.com/nathanhoad/godot_sound_manager/assets/43980777/10402c1c-102b-4fc4-8031-13dd8493fb89

> **Note** Listen to the music in the video

## The code:

I make a `data.gd` file (that save and load the game settings) and set it to autoload (name `Data`):

```gd
var music_volume := 100:
	get:
		return music_volume
	set(value):
		music_volume = value
		
		SoundManager.set_music_volume(float(value) / 100)

var sound_volume := 100:
	get:
		return sound_volume
	set(value):
		sound_volume = value
		
		SoundManager.set_sound_volume(float(value) / 100)
```

In `options_sheet.gd`:

```gd
func _on_spin_box_music_value_changed(value: float) -> void:
	Data.music_volume = int(value)
	printt(Data.music_volume, Data.sound_volume)


func _on_spin_box_sound_value_changed(value: float) -> void:
	Data.sound_volume = int(value)
	printt(Data.music_volume, Data.sound_volume)
```

**Comment by nathanhoad** [comment]
Is there a chance you have the same audio bus for both music and sound effects? I'll add a debug warning for when they match.

**Comment by NNBnh** [comment]
> Is there a chance you have the same audio bus for both music and sound effects?

Yes... Turn out, I didn't pay attention to the document and miss the part that sets the default audio bus. So both music and sound use the same default audio bus (`Master`).

So to anyone who has this problem, just add this code:

```gd
SoundManager.set_default_music_bus("Music")
SoundManager.set_default_sound_bus("Sound")
```

And remember to add those audios bus named `Music` and `Sound` to the project.
